const fakeStudentData = [
  {
    id: "waksket322k",
    username: "Jatin",
    email: "jatintilwani500@gmail.com",
    password: "password",
    image: "https://picsum.photos/200",
    purchasedCourses: [],
  },
  {
    id: "ydJQGJky7eD1",
    username: "Andrew",
    email: "jokurles@ewmeb.sn",
    password: "test1234",
    image: "https://picsum.photos/200",
    purchasedCourses: [],
  },
  {
    id: "Wk2c2mfTM3eFiZ6uf",
    username: "Alvin",
    email: "sat@tu.et",
    password: "test1234",
    image: "https://picsum.photos/200",
    purchasedCourses: [],
  },
  {
    id: "CYeiMIheqk8UFw2CXw9",
    username: "Danny",
    email: "lenban@ven.cr",
    password: "test1234",
    image: "https://picsum.photos/200",
    purchasedCourses: [],
  },
  {
    id: "br7WGbeIGevR4",
    username: "Micheal",
    email: "zam@se.mo",
    password: "test1234",
    image: "https://picsum.photos/200",
    purchasedCourses: [],
  },
];

const fakeCourseData = [
  {
    title: "Introduction to Python Programming",
    description: "Learn the basics of Python programming language.",
    thumbnail: "https://picsum.photos/200",
    creator: "John Doe",
    price: 3200,
    content: [],
  },
  {
    title: "Web Development Fundamentals",
    description: "Explore the essential concepts of web development.",
    thumbnail: "https://picsum.photos/200",
    creator: "Jane Smith",
    price: 4500,
    content: [],
  },
  {
    title: "Machine Learning Essentials",
    description: "Discover the fundamentals of machine learning.",
    thumbnail: "https://picsum.photos/200",
    creator: "Alex Johnson",
    price: 3000,
    content: [],
  },
  {
    title: "Graphic Design Principles",
    description: "Master the basics of graphic design.",
    thumbnail: "https://picsum.photos/200",
    creator: "Emily Brown",
    price: 2000,
    content: [],
  },
  {
    title: "Data Structures and Algorithms",
    description: "Explore essential data structures and algorithms.",
    thumbnail: "https://picsum.photos/200",
    creator: "Chris Wilson",
    price: 5000,
    content: [],
  },
  {
    title: "Digital Marketing Strategies",
    description: "Learn effective digital marketing techniques.",
    thumbnail: "https://picsum.photos/200",
    creator: "Sophia Davis",
    price: 1500,
    content: [],
  },
  {
    title: "Photography Basics",
    description: "Master the fundamentals of photography.",
    thumbnail: "https://picsum.photos/200",
    creator: "Michael Thompson",
    price: 1500,
    content: [],
  },
  {
    title: "Artificial Intelligence Fundamentals",
    description: "Explore the basics of artificial intelligence.",
    thumbnail: "https://picsum.photos/200",
    creator: "Eva Martinez",
    price: 5000,
    content: [],
  },
  {
    title: "Financial Planning and Investment",
    description: "Understand financial planning and investment strategies.",
    thumbnail: "https://picsum.photos/200",
    price: 2500,
    creator: "Daniel Garcia",
    content: [],
  },
  {
    title: "Creative Writing Workshop",
    description:
      "Enhance your writing skills through creative writing exercises.",
    thumbnail: "https://picsum.photos/200",
    price: 1500,
    creator: "Olivia Rodriguez",
    content: [],
  },
];

module.exports = { fakeStudentData, fakeCourseData };
